### ISSUE TITLE
Prompt has 4 duplicated lines 

### ISSUE THREAD

**Issue by louisdecharson** [reobin/typewritten#77] opened 2020-09-15 08:13 UTC
**Describe the bug**
After installing typewritten, I have a prompt of 4 duplicated lines instead of one (see screenshot below).

**To Reproduce**
1. Install the theme using instructions [here](https://typewritten.dev/#/installation?id=oh-my-zsh) for oh-my-zsh.
2. Add `ZSH_THEME="typewritten/typewritten"` to `~/.zshrc`
3. Open a new iTerm2 window

**Expected behavior**
A prompt of one line instead of 4.

**Screenshots**
![Screenshot 2020-09-15 at 10 08 43](https://user-images.githubusercontent.com/3234544/93183572-72d64e80-f73b-11ea-8c7c-41b252edc74d.png)

**Desktop (please complete the following information):**
 - OS: MacOs 10.15.6 

**Additional context**
I've first tried to install typewritten via nom and then remove installation (as it was not working for me).
The issue is the same on all terminal emulator I've tried (iTerm2.app, Terminal.app, shell inside emacs)
The issue is not occurring with another theme.

**Comment by reobin** [comment] 2020-09-15 10:09
Hi @louisdecharson ! Thanks for the report.

Can you tell me more about the failed npm install? Is there any error message while it's installing?

Also, can I take a peak at your zshrc?

**Comment by louisdecharson** [comment] 2020-09-15 11:26
Hello @reobin !
Thank for your swift feedback.
Actually it has not failed, it was just not working. There was no error message.
My  `~/.zshrc`:
```{sh}

ZSH_DISABLE_COMPFIX=true

ZSH_THEME="typewritten/typewritten"

if [[ -n "$INSIDE_EMACS" ]]; then
  plugins=(git)
  ZSH_THEME="robbyrussell"
fi

plugins=(git history history-substring-search brew nanoc zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh


export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:$PATH"


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/louis_de_charsonville/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/louis_de_charsonville/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/louis_de_charsonville/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/louis_de_charsonville/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# Add TeX distribution to PATH
export PATH="/Library/TeX/texbin/:$PATH"
```

**Comment by louisdecharson** [comment] 2020-09-15 11:37
Found the issue !! :) 
It was because of `export code="/Users/louis_de_charsonville/code"`

**Comment by reobin** [comment] 2020-09-15 12:07
Glad to hear it!

It is weird indeed. What does `code` do? curious.

Could you try to source `$ZSH/oh-my-zsh.sh` at the very end of your file? zsh might be reassigning things triggering a prompt refresh.

**Comment by louisdecharson** [comment] 2020-09-15 12:25
Nothing, it's just a repository with code and the variable `$code` is pointing to the repository.
Putting source at then end does not solve the issue :/.

**Comment by reobin** [comment] 2020-09-15 12:40
Not sure about the reasons, but I was able to reproduce it using the exact same variable pointing a directory of mine.

Definitely looks like a bug now, so I'll reopen this. I'll work on it later today

**Comment by reobin** [comment] 2020-09-15 12:49
I found it.

I recently added the `tw_` prefix to all variables to avoid conflicting with the variables of other programs, or simply the user config variables. When there are conflicts, stuff like this (your bug) happens.

I had a variable named `code` representing the return code of an async job. When the return code is defined, it means that something happened to the async worker, and it needs to be reinitialized.

The `code` variable was renamed to `tw_code`, but the condition is still checking for the variable `code` instead of `tw_code`.

Sorry about that 😅 
But thank you for the research you did. The bug could have stayed in the codebase for a while without this bug report.

Do you want to go ahead and update it? The mistake is on line 94 of `typewritten.zsh`.

**Closed** 2020-09-15 13:16 UTC
